
package com.ankit.cxf.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sun Apr 23 22:29:28 IST 2017
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "subResponse", namespace = "http://cxf.ankit.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "subResponse", namespace = "http://cxf.ankit.com/")

public class SubResponse {

    @XmlElement(name = "return")
    private int _return;

    public int getReturn() {
        return this._return;
    }

    public void setReturn(int new_return)  {
        this._return = new_return;
    }

}

